---
title: "Plot 2d SFS"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.retina = 2)
library(tidyverse)
library(ggpubr)
cbp1 <- c("#E69F00", "#56B4E9", "#009E73",
          "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```

This is a note of how to make 2d sfs plot 

```{r funs}
source("scripts/plot2dSFS.R")
plot2 <- function(s,x,y,xlab,ylab){
        dim(s) <- c(x,y)
        s[1] <- NA
        #s[139,237] <-NA
        s[x,y] <- NA
        s<-s/sum(s,na.rm=T)
        pal <- color.palette(c("darkgreen","#00A600FF","yellow","#E9BD3AFF","orange","red4","darkred","black"), space="rgb")
        pplot(s,ylab=ylab,xlab=xlab, pal=pal)
}
```

## Make plots

**For north inshore and offshore**

```{r , echo=FALSE,fig.width=5}
sfs_inshore_offshore<-scan("data/hpc/inshore_offshore/inshore_offshore.folded.2dsfs")
plot2(sfs_inshore_offshore,139,237,"Offshore","North Inshore")
```


**For north inshore and Magnetic Island**

```{r , echo=FALSE}
sfs_NI_MI<-scan("data/hpc/north_MI/NI_MI.folded.2dsfs")
plot2(sfs_NI_MI,43,237,"Magnetic Island","North Inshore")
```

