---
title: "IBS tree"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.retina = 2)
library(tidyverse)
library(ggpubr)
library(ggbreak)
library(knitr)
library(ape)
library(ggtree)
library(phytools)
source("scripts/my_color.R")

df <- read_csv("data/hpc/qc/summary_data.csv") %>% mutate(pop_order=site_order()[pop],
                                                          mapping_rate=as.numeric(sub("%", "", mapping_rate)),
                                                          genome_cov=as.numeric(sub("%", "", genome_cov)))
```

We used angsd to estimate the pairwise distance matrix based on IBS and excluded samples were identified as hybrids for makeing NJ tree.

```{r,fig.align='center',fig.height=9.8,fig.width=3,out.extra='style="transform: rotate(90deg);display: block; margin: auto;"'}

sample_ids <- read_tsv("data/hpc/pca/ind212.txt", col_names = "sample_id",show_col_types = FALSE) %>% pull(sample_id)
ibs_matrix <- read_table("data/hpc/ibs/atenius.ind212.unique_mdust1M_depth.ibs.ibsMat",col_names = F) %>% as.matrix()

ibs_matrix <- ibs_matrix[1:212,1:212]
rownames(ibs_matrix) <- sample_ids
colnames(ibs_matrix) <- sample_ids

ibs_matrix <- ibs_matrix[-which(rownames(ibs_matrix) %in% c("MI-1-1_S10","PI-1-16_S16","DI-2-4_S17","ARL_15_S69")),-which(rownames(ibs_matrix)%in%c("MI-1-1_S10","PI-1-16_S16","DI-2-4_S17","ARL_15_S69"))]

nj_tree <- nj(ibs_matrix)
nj_tree <- midpoint.root(nj_tree)

df <- data.frame(label=nj_tree$tip.label, pop=map_chr(nj_tree$tip.label %>% str_split("_|-"), first))
nj_tree <- full_join(nj_tree,df,by='label')

p<-ggtree(nj_tree) + geom_tippoint(aes(color=pop),size=1,alpha=.8) + scale_color_manual(values = site_colors(), guide="none")
p

#ggsave("s-fig-ibs_njtree.png",height = 6.8,width = 2)
```

We also used this iBS matrix in EEMS excluding samples from Magnetic Island. However, these is not big variation in ibs distances. 

```{r}
ibs_190 <- ibs_matrix[-grep(rownames(ibs_matrix),pattern = "MI"),-grep(rownames(ibs_matrix),pattern = "MI")]
heatmap(ibs_190,symm = T)
```



```{r}

#library(rEEMSplots)
#mcmcpath <- "data/hpc/eems/atenuis_eems-chain1"
#plotpath <- "eems"
#Sys.setenv(R_GSCMD = "/opt/homebrew/bin/gs")

#eems.plots(mcmcpath, plotpath, longlat = TRUE)
```


